---
title: "KS Data"
author: "Josh"
output: html_document
---


```{r echo=FALSE}

library(dplyr)
library(survival)
library(dtplyr)
library(ggplot2)
library(ggfortify)
library(tidyr)
library(lubridate)
library(data.table)
library(splines)
library(survey)
library(mitools)
library(mvtnorm)
library(kableExtra)

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cohort_imp1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4_1.Rda") 
#all_cd4_1 = all_cd4_1 |> filter(!is.na(month_avg_cd4))
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4.Rda") 
patients_all = fread("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Sampling_frame/patients_all.csv")
names(patients_all)="patient"
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long.Rda") 



all_val_long4$R=1

d_1 = all_cohort_imp1 |> filter(patient %in% all_val_long$patient)  |> left_join(all_val_long4[,c('patient','R')]) |> count(patient,stop_d,program,death_y,R) |> mutate(n=NULL,R=if_else(is.na(R),0,R))


#### Single imputation for filling in missing cd4 values in phase 1 and phase 2

#### use one row for all patients in cohort 
d = all_cohort_imp1 |> inner_join(patients_all,by="patient")  
  
## Remove patients w/ dis_d < as.Date("2009-12-01")
d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  

## Add unvalidated CD4 
d2 = d1 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by="patient") |> mutate(cd4_d=if_else(!is.na(year_month),paste(year_month, "-01", sep=""),NA)) |>mutate(cd4_d=as.Date(cd4_d), Diff= cd4_d-as.Date(dis_d)) |> mutate(Diff=if_else(Diff>-183,Diff,NA),Diff=abs(Diff))

#d2 = d1 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by="patient") |> mutate(cd4_d=if_else(!is.na(year_month),paste(year_month, "-01", sep=""),NA)) |>mutate(cd4_d=as.Date(cd4_d), Diff= cd4_d-as.Date(dis_d)) |> mutate(Diff=if_else(Diff>-183,Diff,NA),Diff=abs(Diff))

### limit to date of cd4 closest to KS date of diagnosis (6 months before to 12 months after) 
d3_1= d2|> group_by(patient) |> slice_min(Diff, with_ties = F) |> mutate(cd4_rt=if_else(!is.na(Diff) & !is.na(month_avg_cd4),sqrt(month_avg_cd4),NA))


## Add validated CD4 

d4 = d3_1 |> left_join(all_val_long4[,c("patient","month_avg_cd4_final","cd4_d_final")],by="patient") 


d4$Diff1=d4$cd4_d_final - d4$canc_d_final 
#d4$Diff1=ifelse(d4$Diff1 >-183,d4$Diff1,NA)
d4$Diff1=ifelse(d4$Diff1 >-183,d4$Diff1,NA)

d4$Diff1=abs(d4$Diff1)

d5= d4|> group_by(patient) |> slice_min(Diff1, with_ties = F) |> mutate(cd4_rt_final=if_else(!is.na(Diff1) & !is.na(month_avg_cd4_final),sqrt(month_avg_cd4_final),NA))

d6 = d5 |> filter(V==0 & !is.na(dis_d) | (V==1 & !is.na(dis_d) & !is.na(canc_d_final) & as.Date(canc_d_final)>=as.Date("2009-12-01"))) 

# d6 = d6 |> mutate(cd4_rt=if_else(Diff < 183,cd4_rt,NA),cd4_rt_final=if_else(Diff1 < 183,cd4_rt_final,NA)) |> mutate(age=as.numeric(round((as.Date(dis_d)-as.Date(birth_d))/365.25,1)), year = if_else(as.Date(dis_d)<as.Date("2010-01-01"),
#  as.numeric("2010"),as.numeric(substr(dis_d,1,4))),art_ind = if_else(is.na(art_sd),0,if_else(as.Date(art_sd)<as.Date(dis_d),1,0)),age_final=as.numeric(round((as.Date(canc_d_final)-as.Date(birth_d_final))/365.25,1)), year_final = if_else(as.Date(canc_d_final)<as.Date("2010-01-01"),
#  as.numeric("2010"),as.numeric(substr(canc_d_final,1,4))),art_ind_final = if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(canc_d_final),1,0)))

d6 = d6 |> mutate(cd4_rt=if_else(Diff < 183,cd4_rt,NA),cd4_rt_final=if_else(Diff1 < 183,cd4_rt_final,NA)) |> mutate(age=as.numeric(round((as.Date(dis_d)-as.Date(birth_d))/365.25,1)), year = if_else(as.Date(dis_d)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(dis_d,1,4))),art_ind = if_else(is.na(art_sd),0,if_else(as.Date(art_sd)<as.Date(dis_d),1,0)),age_final=as.numeric(round((as.Date(canc_d_final)-as.Date(birth_d_final))/365.25,1)), year_final = if_else(as.Date(canc_d_final)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(canc_d_final,1,4))),art_ind_final = if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(canc_d_final),1,0)))


d6 = d6 |>mutate(time=if_else(is.na(death_d),as.numeric(as.Date(stop_d)-as.Date(dis_d))+1,as.numeric(as.Date(death_d)-as.Date(dis_d))+1),canc_yr=if_else(as.Date(dis_d) >= as.Date("2010-01-01"), as.numeric(format(dis_d,'%Y')), as.numeric("2010")), death_ind=if_else(is.na(death_d),0,1)) |>  mutate(time_final=if_else(is.na(death_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(canc_d_final))+1,as.numeric(as.Date(death_d_final)-as.Date(canc_d_final))+1),canc_yr_final=if_else(as.Date(canc_d_final) >= as.Date("2010-01-01"), as.numeric(format(canc_d_final,'%Y')), as.numeric("2010")), death_ind_final=if_else(is.na(death_d_final),0,1))


d6 = d6 |> mutate(remove = if_else(dis_d < enrol_d - 60,1,0),remove_final =  if_else(!is.na(canc_d_final) & canc_d_final < enrol_d_final - 60,1,0)) |> filter(remove == 0 & remove_final==0) 


d_2 = d_1 |> filter(patient %in% d6$patient)
mod_w = glm(R ~ stop_d + program + death_y, family=binomial,data = d_2)
mod_p<- mod_w$fitted.values
d_p = data.frame(d_2,p_est=mod_p)

# 
# sum(is.na(d6[d6$V==1,]$cd4_rt_final))
# length(d6[d6$V==1,]$cd4_rt_final)

### imputation for phase 1 cd4 values based on error prone variables
    mod5 = lm(cd4_rt ~  male +program+ ns(age,df=4) + year +art_ind + ns(time,df=4)*death_ind, data= d6[!is.na(d6$cd4_rt),]) 
   ## to easily get design matrix for the full cohort
    d6_1 = d6 |> mutate(cd4_rt=1)
    v3=model.matrix(terms(mod5),d6_1)
    beta2 = mod5$coefficients
    vcov2 = vcov(mod5)
    rmvs2=rmvnorm(n=1,beta2,vcov2)
    rmvs2 = as.vector(rmvs2)
    cd4_rt_new = as.vector((v3 %*% rmvs2) + sample(resid(mod5),1))
    d6$cd4_rt_init_imp=if_else(is.na(d6$cd4_rt),cd4_rt_new,d6$cd4_rt)
    ### any imputed CD4<0 assign a 1
    d6$cd4_rt_init_imp=if_else(d6$cd4_rt_init_imp<0,1,d6$cd4_rt_init_imp)

  ### imputation for phase 2 cd4 values
  #d6_val = d6 |> filter(!is.na(canc_d_final))
  
  mod6 = lm(cd4_rt_final ~  male_final +program+ ns(age_final,df=4) + ns(cd4_rt_init_imp,df=4) + year_final +art_ind_final + ns(time_final,df=4)*death_ind_final, data= d6)
    ## to easily get design matrix for phase 2
  
  d6_1 = d6 |> mutate(cd4_rt_final=1)
   v4=model.matrix(terms(mod6),d6_1)
  beta2 = mod6$coefficients
  vcov2 = vcov(mod6)
  rmvs2=rmvnorm(n=1,beta2,vcov2)
  rmvs2 = as.vector(rmvs2)
  cd4_rt_final_new = as.vector((v4 %*% rmvs2) + sample(resid(mod6),1))
  d6_phase2 = d6[d6$V==1,]
  d6_phase2$cd4_rt_imp_final=if_else(is.na(d6_phase2$cd4_rt_final),cd4_rt_final_new,d6_phase2$cd4_rt_final)
  d6_phase2$cd4_rt_imp_final=if_else(d6_phase2$cd4_rt_imp_final<0,1,d6_phase2$cd4_rt_imp_final)
  d7 = rbind(d6[d6$V==0,],d6_phase2)

# d7 = d7 |>mutate(time=if_else(is.na(death_d),as.numeric(as.Date(stop_d)-as.Date(dis_d))+1,as.numeric(as.Date(death_d)-as.Date(dis_d))+1),canc_yr=if_else(as.Date(dis_d) >= as.Date("2010-01-01"), as.numeric(format(dis_d,'%Y')), as.numeric("2010")), death_ind=if_else(is.na(death_d),0,1)) |>  mutate(time_final=if_else(is.na(death_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(canc_d_final)),as.numeric(as.Date(death_d_final)-as.Date(canc_d_final))),canc_yr_final=if_else(as.Date(canc_d_final) >= as.Date("2010-01-01"), as.numeric(format(canc_d_final,'%Y')), as.numeric("2010")), death_ind_final=if_else(is.na(death_d_final),0,1))

## IPW
#load(file="~/Desktop/PhD/Research/KS_Data/Code/wgts_by_hand.Rda")
load(file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/strata.Rda")
## nonresponse probabilities
#load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/d_p.Rda") 

d_tte_c= merge(x=d7,y=d_c2,all.x=TRUE,by="patient")
d_tte_c= merge(x=d_tte_c,y=d_p[,c('patient','p_est')],all.x=TRUE,by="patient")

#designMF1= twophase(id=list(~1,~1),weights=list(~1,~w),subset=~V==1, data=d_tte_c,method="approx")
#ipw_tte_c2 = svycoxph(Surv(time_final,death_ind_final) ~ male_final+program+I(age_final/10)+canc_yr_final+art_ind_final + cd4_rt_imp_final,design=designMF1)

#################################################################################################################
#### IPW with estimated weights and nonresponse probabilities from the TTE analysis cohort

mod_w = glm(V ~ strata, family=binomial,data = d_tte_c)
mod_p <- mod_w$fitted.values
d_tte_cw = data.frame(d_tte_c,p_est_overall=mod_p)
d_tte_cw = d_tte_cw |> mutate(w_est = 1/(p_est_overall*p_est))

designMF6 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata),subset=~V==1, data=d_tte_cw,method="approx")
ipw_tte_c2 = svycoxph(Surv(time_final,death_ind_final) ~ male_final+program+I(age_final/10)+I(canc_yr_final-2010)+art_ind_final + cd4_rt_imp_final,design=designMF6)

#################################################################################################################

## Generalized raking

### year
mod_ehr_tte = coxph(Surv(time,death_ind) ~ I(year-2010), data = d7)

  
  naiveInfl1 = resid(mod_ehr_tte,type="dfbeta",weighted=FALSE)
  #colnames(naiveInfl1)=paste("INF", 1:ncol(naiveInfl1), sep="")
  d7_2=cbind(d_tte_cw,INF1=naiveInfl1) 

  ## GR + MI
  designMF2 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d7_2,subset=~V==1,method="approx")
  Ninflcal1<- survey::calibrate(designMF2,formula=~INF1,phase=2,calfun="raking") 
  fit_gr_tte1 = svycoxph(Surv(time_final,death_ind_final) ~ I(year_final-2010),design=Ninflcal1)  

### year and region

mod_ehr_tte = coxph(Surv(time,death_ind) ~ I(year-2010)+program, data = d7)

  
  naiveInfl1 = resid(mod_ehr_tte,type="dfbeta",weighted=FALSE)
  colnames(naiveInfl1)=paste("INF", 1:ncol(naiveInfl1), sep="")
  d7_2=cbind(d_tte_cw,naiveInfl1) 
  infs_eq <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl1), collapse = ' + ')))
  
  ## GR + MI
  designMF2 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d7_2,subset=~V==1,method="approx")
  Ninflcal1<- survey::calibrate(designMF2,formula=infs_eq,phase=2,calfun="raking") 
  fit_gr_tte2 = svycoxph(Surv(time_final,death_ind_final) ~ I(year_final-2010)+program,design=Ninflcal1)    
  
### year and region interaction  
  
mod_ehr_tte = coxph(Surv(time,death_ind) ~ I(year-2010)*program, data = d7)

  
  naiveInfl1 = resid(mod_ehr_tte,type="dfbeta",weighted=FALSE)
  colnames(naiveInfl1)=paste("INF", 1:ncol(naiveInfl1), sep="")
  d7_2=cbind(d_tte_cw,naiveInfl1) 
  infs_eq <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl1), collapse = ' + ')))
  
  ## GR + MI
  designMF2 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d7_2,subset=~V==1,method="approx")
  Ninflcal1<- survey::calibrate(designMF2,formula=infs_eq,phase=2,calfun="raking") 
  fit_gr_tte3 = svycoxph(Surv(time_final,death_ind_final) ~ I(year_final-2010)*program,design=Ninflcal1)    
  
###################################  

lst= list(fit_gr_tte1,fit_gr_tte2,fit_gr_tte3)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0)))), betas + 1.96*(sqrt(diag(vcov(res0)))))
  res2[[j]] <- exp(cis3)
}


ktab9_tte = cbind(OR = c(format(round(res2[[1]][,1],2),nsmall=2),"-","-"), CI_95_percent = c(paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),"-","-"),OR = c(format(round(res2[[2]][,1],2),nsmall=2),"-"), CI_95_percent = c(paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),"-"),OR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)))

save(ktab9_tte,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/ktab9_tte.Rda") 


rownames(ktab9_tte)=c('Year','East Africa','Year x East Africa')
ktab9 <- kable(ktab9_tte,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2))%>%add_header_above(c(" ","Mortality" = 6))

```



```{r}

### weighted K-M curve using IPW
library(gridExtra)

library(survMisc)

d_tte_cw$time_final1=d_tte_cw$time_final/365.25
s11=survfit(Surv(time_final1,death_ind_final)~1,subset = V==1, type="kaplan-meier", data=d_tte_cw, weights = w_est)
s1= s11%>% ggplot2::autoplot(conf.int=T,surv.linetype = 'dashed',censor=FALSE,xlab="Time (years)", ylab="Survival Probability", main="Overall survival from KS Diagnosis")

s12=data.frame(s11$time,s11$surv,s11$lower, s11$upper)


d_tte_cw_1=d_tte_cw |> mutate(program1=factor(program,labels=c("CCASAnet", "IeDEA-EA")))

s2=survfit(Surv(time_final1,death_ind_final)~program1,subset = V==1, type="kaplan-meier", data=d_tte_cw_1, weights = w_est) %>% ggplot2::autoplot(conf.int=T,surv.linetype = 'dashed',censor=FALSE,xlab="Time (years)", ylab="Survival Probability", main="Survival from KS Diagnosis by Region") + labs(color = "Region", fill = "Region")  

grid.arrange(s1, s2, nrow=2)

```


```{r}

### weighted LTFU 

library(data.table)
library(dplyr)
library(stringr)

dcc1 = d_tte_cw |> filter(V==1) |> mutate(center=word(strata,1))

d_c=fread("/Users/joshslone/Desktop/PhD/Research/KS_Data/Code/dat_base_mi.csv") 
  
d_c = d_c |> mutate(center=word(strata,1))
#patient with multiple centers, chose the most recent visit date as their center (reduces calculated LTFU rate)

# 95% closure for each center to determine LTFU
l_dates <- d_c %>% group_by(center) %>% 
  summarise(ltfu_date=quantile(stop_d, probs = 0.95, type = 1)) 

# determine which patients were lost to follow by having their last visit prior to one year before the 95% date for that center 

v_ltfu <- dcc1 %>% left_join(l_dates) %>% mutate(LTFU=if_else(as.Date(ltfu_date)-as.Date(l_alive_d_final)>365 & death_y_final==0,1,0))

ltfu_summary<-v_ltfu%>%group_by(program)%>%summarise(n=n(),LTFU=sum(LTFU),LTFU_Percent=round(100*sum(LTFU)/n(),2))

### weighted death KS cohort sum(v_ltfu[v_ltfu$death_y_final==1,]$w_est)/sum(v_ltfu$w_est)


### weighted death EA sum(v_ltfu[v_ltfu$death_y_final==1 & v_ltfu$program==1,]$w_est)/sum(v_ltfu[v_ltfu$program==1,]$w_est)

### weighted death LA sum(v_ltfu[v_ltfu$death_y_final==1 & v_ltfu$program==0,]$w_est)/sum(v_ltfu[v_ltfu$program==0,]$w_est)

# sum(v_ltfu[v_ltfu$LTFU==1,]$w_est)
# sum(v_ltfu[v_ltfu$program==0 & v_ltfu$LTFU==1,]$w_est)/sum(v_ltfu[v_ltfu$program==0,]$w_est)
# sum(v_ltfu[v_ltfu$program==1 & v_ltfu$LTFU==1,]$w_est)/sum(v_ltfu[v_ltfu$program==1,]$w_est)
# sum(v_ltfu[v_ltfu$LTFU==1,]$w_est)/sum(v_ltfu$w_est)
```

```{r}

### Overall LTFU for phase-1

d_c=fread("/Users/joshslone/Desktop/PhD/Research/KS_Data/Code/dat_base_mi.csv") 
  
d_c = d_c |> mutate(center=word(strata,1))
#patient with multiple centers, chose the most recent visit date as their center (reduces calculated LTFU rate)

# 95% closure for each center to determine LTFU
l_dates <- d_c |> filter(death_y==0) %>% group_by(center) %>% 
  summarise(ltfu_date=quantile(stop_d, probs = 0.95, type = 1)) 

# determine which patients were lost to follow by having their last visit prior to one year before the 95% date for that center 

all_ehr_ltfu <- d_c  %>%  left_join(l_dates) %>% mutate(LTFU=if_else(as.Date(ltfu_date)-as.Date(stop_d)>365 & death_y==0,1,0))

ltfu_summary<-all_ehr_ltfu%>%group_by(program)%>%summarise(n=n(),LTFU=sum(LTFU),LTFU_Percent=round(100*sum(LTFU)/n(),2))



ltfu_summary_ks<-all_ehr_ltfu%>% filter(ks_y==1) |> group_by(program)%>%summarise(n=n(),LTFU=sum(LTFU),LTFU_Percent=round(100*sum(LTFU)/n(),2))

#ltfu_summary_ks<-all_ehr_ltfu%>% filter(ks_y==1) |> summarise(n=n(),LTFU=sum(LTFU),LTFU_Percent=round(100*sum(LTFU)/n(),2))

```

