---
title: "KS Data"
author: "Josh"
output: html_document
---


```{r echo=FALSE}

library(dplyr)
library(dtplyr)
library(collapse)
library(tidyr)
library(data.table)
library(splines)
library(survey)
library(mitools)
library(mvtnorm)
library(kableExtra)

```



```{r}
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cohort_imp1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4_1.Rda") 
#all_cd4_1 = all_cd4_1 |> filter(!is.na(month_avg_cd4))
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4.Rda") 
patients_all = fread("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Sampling_frame/patients_all.csv")
names(patients_all)="patient"



load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long.Rda") 



all_val_long4$R=1

d_1 = all_cohort_imp1 |> filter(patient %in% all_val_long$patient)  |> left_join(all_val_long4[,c('patient','R')]) |> count(patient,stop_d,program,death_y,R) |> mutate(n=NULL,R=if_else(is.na(R),0,R))

```


```{r}
#### Single imputation for filling in missing cd4 values in phase 1 and phase 2

#### use one row for all patients in cohort 
d = all_cohort_imp1 |> inner_join(patients_all,by="patient")  
  
## Remove patients w/ dis_d < as.Date("2009-12-01")
d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  

  #### expanded monthly data
  
  #add rows for each month
  setDT(d1)
  # floor start and end month
  ## start_d is the earlier of enrol_d and earliest cd4_d
  ## stop_d is the latest of l_alive_d,last_visit_d,death_d
  d1[, start_month := lubridate::floor_date(start_d, unit = "month")]
  d1[, end_month := lubridate::floor_date(stop_d, unit = "month")]

    d2<-d1[, .(year_month = format(seq(start_month, end_month, by = "1 month"), "%Y-%m")), by = .(patient,birth_d,birth_d_final,enrol_d,enrol_d_final,male, male_final,dis_d, canc_d_final,art_sd, recart_d_final, death_y,death_y_final,death_d,death_d_final,l_alive_d_final, start_d,start_d_final, stop_d, program,V)]
    
    ### merge cd4 values in by year_month from phase 1 and phase 2 long datasets and create variables below, carry forward cd4 12 months and then cutoff at 2010 forward
  
## Add unvalidated CD4 and validated CD4 
d3 = d2 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by=c("patient","year_month")) |> left_join(all_val_long4[,c("patient","year_month","month_avg_cd4_final")],by=c("patient","year_month")) 


  d3=d3 %>% lazy_dt() |> group_by(patient) %>% mutate(new_v = if_else(is.na(month_avg_cd4),NA,row_number())) |> fill(new_v) |> mutate(row_diff = row_number()-new_v,cd4_1=month_avg_cd4) |> fill(cd4_1,.direction = "down") |> mutate(cd4_2=cd4_1) |> fill(cd4_1,.direction = "up") |>fill(new_v,.direction = "up") |> mutate(cd4=if_else(row_number() < 7 & new_v <=7, cd4_1, cd4_2)) |> ungroup() |> as.data.frame()
  
 d4=d3 %>% lazy_dt() |> group_by(patient) %>% mutate(new_v = if_else(is.na(month_avg_cd4_final),NA,row_number())) |> fill(new_v) |> mutate(row_diff = row_number()-new_v,cd4_1=month_avg_cd4_final) |> fill(cd4_1,.direction = "down") |> mutate(cd4_2=cd4_1) |> fill(cd4_1,.direction = "up") |>fill(new_v,.direction = "up") |> mutate(cd4_final=if_else(row_number() < 7 & new_v <=7, cd4_1, cd4_2))  |> ungroup() |> as.data.frame()
  
## eligibility criteria of removing prevalent cases and KS cases >60 days before enrollment; adding ks indicator for imputation
 
# d5 = d4 |> mutate(prevalent = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60 & dis_d >= enrol_d - 60,1,0)) |> mutate(prevalent_final = if_else(V==0,0, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60 & canc_d_final >= enrol_d_final - 60,1,0))) |> filter(prevalent == 0 &  prevalent_final==0 & (is.na(canc_d_final) | as.Date(canc_d_final)>=as.Date("2009-12-01"))) 

d5 = d4 |> mutate(prevalent_remove = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60,1,0)) |> mutate(prevalent_remove_final = if_else(V==0,0, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60,1,0))) |> filter(prevalent_remove == 0 &  prevalent_remove_final==0 & (is.na(canc_d_final) | as.Date(canc_d_final)>=as.Date("2009-12-01"))) 

## Age each month
d5$age<-as.numeric(round((as.Date(paste(d5$year_month, "-01", sep=""))-d5$birth_d)/365.25,1))
d5$age_final<-as.numeric(round((as.Date(paste(d5$year_month, "-01", sep=""))-d5$birth_d_final)/365.25,1))

## ART has started indicator
d5$art_ind<-ifelse(is.na(d5$art_sd) | d5$art_sd > as.Date(paste(d5$year_month, "-01", sep="")),0,1)
d5$art_ind_final<-ifelse(is.na(d5$recart_d_final) | d5$recart_d_final > as.Date(paste(d5$year_month, "-01", sep="")),0,1)

## Add year to each row
d5$year<-as.numeric(substr(d5$year_month,1,4)) 

d5 = d5 |> lazy_dt() |> mutate(ks_year_month = format(dis_d, "%Y-%m"), ks_year_month_final = format(canc_d_final, "%Y-%m"))  |> mutate(ks_ind = if_else(!is.na(dis_d) & ks_year_month == year_month,1,0), ks_ind_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final) & ks_year_month_final == year_month & as.Date(canc_d_final) >= as.Date("2009-12-01"),1,0))) |> filter(program == 1 & year_month >= "2009-12" | program == 0 & year_month >= "2010-01" )  |> ungroup() |> as.data.frame()

d5 = d5 |> lazy_dt() |>  group_by(patient) |> mutate(cd4_rt=sqrt(cd4),cd4_rt_final=sqrt(cd4_final),row=row_number()) |> ungroup() |> as.data.frame()

# 
# d6 = d5 |> lazy_dt() |> mutate(ks=if_else(!is.na(dis_d),1,0),ks_final=if_else(!is.na(canc_d_final),1,0), start_d1=if_else(as.Date(start_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(start_d)),stop_d1=if_else(as.Date(stop_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(stop_d)),dis_d1=if_else(as.Date(dis_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(dis_d)),start_d_final1=if_else(as.Date(start_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(start_d_final)), canc_d_final1=if_else(as.Date(canc_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(canc_d_final)),time=if_else(is.na(dis_d),as.numeric(as.Date(stop_d)-as.Date(start_d1))+1,as.numeric(as.Date(dis_d1)-as.Date(start_d1))+1),time_final=if_else(is.na(canc_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(start_d_final1))+1,as.numeric(as.Date(canc_d_final1)-as.Date(start_d_final1))+1)) |> ungroup() |> as.data.frame()

d6 = d5 |> lazy_dt() |> mutate(ks=if_else(!is.na(dis_d),1,0),ks_final=if_else(!is.na(canc_d_final),1,0), enrol_d1=if_else(as.Date(enrol_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(enrol_d)),stop_d1=if_else(as.Date(stop_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(stop_d)),dis_d1=if_else(as.Date(dis_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(dis_d)),enrol_d_final1=if_else(as.Date(enrol_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(enrol_d_final)), canc_d_final1=if_else(as.Date(canc_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(canc_d_final)),time=if_else(is.na(dis_d),as.numeric(as.Date(stop_d)-as.Date(enrol_d1))+1,as.numeric(as.Date(dis_d1)-as.Date(enrol_d1))+1),time_final=if_else(is.na(canc_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(enrol_d_final1))+1,as.numeric(as.Date(canc_d_final1)-as.Date(enrol_d_final1))+1),enrol_d_year_month=format(enrol_d, "%Y-%m")) |> ungroup() |> as.data.frame()


### remove months prior to the month of enrollment
d6 = d6 |> filter(year_month>=enrol_d_year_month & year_month>="2010-01") 

#d6 = d6 |> mutate(keep=if_else(V==1 & art_ind == 1 & art_ind_final==1 | V==0 & art_ind == 1 & art_ind_final==0, 1, 0))  |> filter(keep==1)

#d6 = d6 |> filter(year_month>=enrol_d_year_month & year_month>="2015-01" & !is.na(art_sd) & as.Date(art_sd) >= as.Date("2015-01-01")) 
#<<<<<< run next




### cd4 missingness


# ch= d6 |>  group_by(patient) |> filter(V==1 & row_number()==1)
# 
# ch1=ch[is.na(ch$cd4_rt_final),]
# 
# ch2=length(unique(d6[!is.na(d6$cd4_rt_final) & d6$V==1,]$patient))

### 255150 total and 203880 have at least one

### 830 total and 96 have at least one


rm(list=setdiff(ls(), c("d6","d_1")))

    ### imputation for phase 1 cd4 values based on error prone variables
    mod5 = lm(cd4_rt ~  male +program+ ns(age,df=4) + year +  ks*ns(time,df=4), data= d6[d6$row==1,]) 
   ## to easily get design matrix for the full cohort
    d6_1 = d6 |> mutate(cd4_rt=1)
    v3=model.matrix(terms(mod5),d6_1)
    beta2 = mod5$coefficients
    vcov2 = vcov(mod5)
    rmvs2=rmvnorm(n=1,beta2,vcov2)
    rmvs2 = as.vector(rmvs2)
    cd4_rt_new = as.vector((v3 %*% rmvs2) + sample(resid(mod5),1))
    d6$cd4_rt_init_imp=if_else(d6$row==1 & is.na(d6$cd4_rt),cd4_rt_new,d6$cd4_rt)
    ### any imputed CD4<0 assign a 1
    d6$cd4_rt_init_imp=if_else(d6$cd4_rt_init_imp<0,1,d6$cd4_rt_init_imp)
    
    d6 = d6 |> fill(cd4_rt_init_imp)

  ### imputation for phase 2 cd4 values
  mod6 = lm(cd4_rt_final ~  male_final +program+ ns(age_final,df=4) + ns(cd4_rt_init_imp,df=4) + year + ks_final*ns(time_final,df=4), data= d6[d6$row==1 & d6$V==1,])
    ## to easily get design matrix for phase 2
  d5_2=d6[d6$V==1,]
  d6_1 = d5_2 |> mutate(cd4_rt_final=1)
   v4=model.matrix(terms(mod6),d6_1)
  beta2 = mod6$coefficients
  vcov2 = vcov(mod6)
  rmvs2=rmvnorm(n=1,beta2,vcov2)
  rmvs2 = as.vector(rmvs2)
  cd4_rt_final_new = as.vector((v4 %*% rmvs2) + sample(resid(mod6),1))
  d5_2$cd4_rt_imp_final=if_else(d5_2$row==1 & d5_2$V==1 & is.na(d5_2$cd4_rt_final),cd4_rt_final_new,d5_2$cd4_rt_final)
  d5_2$cd4_rt_imp_final=if_else(d5_2$cd4_rt_imp_final<0,1,d5_2$cd4_rt_imp_final)
    d5_2 = d5_2 |> fill(cd4_rt_imp_final)
    d6$cd4_rt_imp_final = NA
    d6 = rbind(d6[d6$V==0,],d5_2) 
    

d6_val = d6[d6$V==1,] |> mutate(enrol_d_final_year_month=format(enrol_d_final1, "%Y-%m")) |> filter(enrol_d_final_year_month <= year_month)
  
suppressWarnings({d_inc_val=   d6_val |> lazy_dt() |> group_by(patient) |> mutate(ct=rleid(cd4_rt_imp_final)) |>  filter(row_number() <= min(which(ks_ind_final == 1)))  |> ungroup() |> group_by(patient,year,art_ind_final,cd4_rt_imp_final,ct,birth_d_final,enrol_d_final1) |> summarize(ks_ind_final=max(ks_ind_final),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25 ,pys_final=n/12) |> ungroup() |> as.data.frame()})

# suppressWarnings({d_inc_val=   d6[d6$V==1,] |> lazy_dt() |> group_by(patient) |> mutate(ct=rleid(cd4_rt_imp_final)) |>  filter(row_number() <= min(which(ks_ind_final == 1)))  |> ungroup() |> group_by(patient,year,art_ind_final,cd4_rt_imp_final,ct,birth_d_final,enrol_d_final) |> summarize(ks_ind_final=max(ks_ind_final),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25 ,pys_final=n/12) |> ungroup() |> as.data.frame()})
    
d_inc_val2 = d_inc_val |> lazy_dt() |> left_join(unique(d6[d6$V==1,c("patient","V","program","male_final")])) |> mutate(V1=V) |> ungroup() |> as.data.frame()

suppressWarnings({d_inc =   d6 |> lazy_dt() |> group_by(patient)|> mutate(ct=rleid(cd4_rt_init_imp)) |>  filter(row_number() <= min(which(ks_ind == 1)))  |> ungroup() |> group_by(patient,year,art_ind,cd4_rt_init_imp,ct,birth_d,enrol_d) |> summarize(ks_ind=max(ks_ind),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d)/365.25 ,pys=n/12) |> ungroup() |> as.data.frame()})

d_inc2 = d_inc  |> lazy_dt() |> left_join(unique(d6[,c("patient","V","program","male")])) |> ungroup() |> as.data.frame()
d_inc2$year1 = ifelse(d_inc2$year==2009,2010,d_inc2$year)

mod_ehr_inc = glm(ks_ind ~ male+program+I(age/10)+I(year1-2010)+art_ind + cd4_rt_init_imp,offset = log(pys/1000),data= d_inc2, family = poisson)


### intersection between phase 1 and phase 2
d_inc_val3 = d_inc2 |> left_join(d_inc_val2[,c("patient","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final")]) 
d_inc_val3$year1 = ifelse(d_inc_val3$year==2009,2010,d_inc_val3$year)


### Get overlapping timeframes
## get date ranges for each patient who was validated based on their phase 1 and phase 2 data
### phase 1
cc1=d_inc2[d_inc2$V==1,] |> lazy_dt() |> group_by(patient) |> summarize(n1=max(row_number()),d_min1=min(min_date),d_max1=max(max_date)) |> ungroup() |> as.data.frame()
### phase 2
cc2=d_inc_val2[d_inc_val2$V==1,] |> lazy_dt() |> group_by(patient) |> summarize(n2=max(row_number()),d_min2=min(min_date),d_max2=max(max_date)) |> ungroup() |> as.data.frame()

### phase-1 and phase-2 date ranges and rows for V==1
cc3=cc1 |> left_join(cc2) |> mutate(min_date1= pmax(d_min1,d_min2),max_date1= pmin(d_max1,d_max2))

#### same number of rows and same date range
patients1_1 = cc3 |> filter(n1==n2 & d_min1==d_min2 & d_max1==d_max2)

#### different number of rows or different date range
patients1_2 = cc3 |> filter(n1!=n2 | d_min1!=d_min2 | d_max1!=d_max2)

#######################################################################################################################################
#######################################################################################################################################
## deal with 109 patients with differing number of rows or different date range between phase 1 and phase 2
### phase 1
d_inc2_v0 = d_inc2[d_inc2$V==1,] |> inner_join(patients1_2[,c('patient','min_date1','max_date1')]) |> filter(min_date>=min_date1 & max_date<=max_date1)
### phase 2
d_inc_val2_v0 = d_inc_val2[d_inc_val2$V==1,] |> inner_join(patients1_2[,c('patient','min_date1','max_date1')])  |> filter(min_date>=min_date1 & max_date<=max_date1)

d_all1 = d_inc2_v0 |> full_join(d_inc_val2_v0[,c("patient","birth_d_final","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final","V1")]) 
d_all1$year1 = ifelse(d_all1$year==2009,2010,d_all1$year)

d_all2 = d_all1 |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date)

### updated rows for 109 patients
d_all3_2 = d_all2 |> group_by(patient) |> filter(min_date!=lag(min_date) | max_date!=lead(max_date) | row_number()==1)  |> filter(min_date!=lag(min_date) | max_date!=lead(min_date) | row_number()==1) |> mutate(max_date1=if_else(min_date>lag(max_date) & max_date==lead(max_date) & min_date<lead(max_date),min_date,max_date),max_date1=if_else(is.na(max_date1),max_date,max_date1)) |> mutate(max_date2=if_else(min_date<lag(max_date1) & max_date1==lead(max_date1),lag(max_date1),max_date1),max_date2=if_else(is.na(max_date2),max_date1,max_date2)) |> filter(min_date != lag(min_date) | row_number()==1) |> mutate(max_date=max_date2,max_date1=NULL,max_date2=NULL)

## deal with patients with same number of rows and date ranges between phase 1 and phase 2

### phase 1
d_inc2_v1 = d_inc2[d_inc2$V==1,] |> inner_join(patients1_1[,c('patient','min_date1','max_date1')]) |> filter(min_date>=min_date1 & max_date<=max_date1)
### phase 2
d_inc_val2_v1 = d_inc_val2 |> inner_join(patients1_1[,c('patient','min_date1','max_date1')])  |> filter(min_date>=min_date1 & max_date<=max_date1)

## limit patients with same number of rows and overall date ranges to those with different dates on individual rows
### 702/722 have the exact same dates on each row, 20 do not have the same dates on each row

d_all5 = d_inc2_v1 |> full_join(d_inc_val2_v1[,c("patient","birth_d_final","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final","V1")]) |> group_by(patient) |> filter(any(is.na(V) | is.na(V1)))

d_all6 = d_all5 |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date) 

### updated rows for 20 patients who do not have the same dates on each row
d_all7 = d_all6 |> group_by(patient) |> filter(min_date!=lag(min_date) | max_date!=lead(max_date) | row_number()==1) |> mutate(max_date1=if_else(max_date==lead(max_date) & min_date<lag(max_date),lag(max_date),max_date),max_date1=if_else(is.na(max_date1),max_date,max_date1)) |> filter(min_date!=lag(min_date) | max_date1!=lead(max_date1)) |> mutate(max_date1=if_else(min_date==lag(max_date1) & max_date1==lead(max_date1),lag(max_date1),max_date1)) |> filter(min_date!=lag(min_date) | max_date1!=lead(max_date1) | row_number()==1)|>
mutate(min_date1=if_else(min_date==lag(min_date) & max_date1==lead(min_date),max_date1,min_date)) |> filter(min_date1!=lag(min_date1) | min_date1!=lag(max_date1) | row_number()==1)|> mutate(max_date2=if_else(max_date1==lead(max_date1),min_date1,max_date1),max_date2=if_else(is.na(max_date2),max_date1,max_date2)) |> mutate(min_date=min_date1,max_date=max_date2,min_date1=NULL,max_date1=NULL,max_date2=NULL)



d_c = d_inc2_v1 |> filter(!(patient %in% d_all5$patient))

### rows that match for 728 patients
d_c1 = d_c |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date)

### all rows for validated patients
prows= rbind(d_all3_2,d_all7,d_c1) |> arrange(patient,min_date)


prows1 = prows |> left_join(d_inc_val2,join_by(patient, min_date>=min_date,   min_date<=max_date, max_date<=max_date, max_date>=min_date)) |> mutate(min_date=min_date.x,max_date=max_date.x,min_date.x=NULL,max_date.x=NULL,min_date.y=NULL,max_date.y=NULL)

prows2 = prows1 |> left_join(d_inc2[d_inc2$V==1,],join_by(patient, min_date>=min_date,   min_date<=max_date, max_date<=max_date, max_date>=min_date)) |> mutate(min_date=min_date.x,max_date=max_date.x,min_date.x=NULL,max_date.x=NULL,min_date.y=NULL,max_date.y=NULL,ct.x=NULL,ct.y=NULL,n.x=NULL,n.y=NULL,year=year.x,V=V.x,program=program.x) |> mutate(year.x=NULL,year.y=NULL,V.x=NULL,V.y=NULL,pys=NULL,pys_final=NULL,age=NULL,program.x=NULL,program.y=NULL) |> mutate(n=as.numeric(substr(max_date,6,7))-as.numeric(substr(min_date,6,7))+1) |> mutate(age = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d)/365.25,age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25,pys=n/12,pys_final=n/12)


d_inc2_c = d_inc2 |> filter(!(patient %in% unique(prows2$patient)))

p_all= rbind(prows2,d_inc2_c)


d_2 = d_1 |> filter(patient %in% unique(p_all$patient))
mod_w = glm(R ~ stop_d + program + death_y, family=binomial,data = d_2)
mod_p<- mod_w$fitted.values
d_p = data.frame(d_2,p_est=mod_p)

#load(file="~/Desktop/PhD/Research/KS_Data/Code/wgts_by_hand.Rda")
load(file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/strata.Rda")
#################################################################################################################
#### estimated weights including nonresponse probabilities from the incidence analysis cohort
#load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/d_p.Rda") 
pb1=p_all |> left_join(d_c2,by="patient") |> count(patient,strata,V) |> left_join(d_p[,c('patient','p_est')],by="patient")
mod_w = glm(V ~ strata, family=binomial,data = pb1)
mod_p <- mod_w$fitted.values
pb2 = data.frame(pb1,p_est_overall=mod_p)
pb2 = pb2 |> mutate(w_est = 1/(p_est_overall*p_est))
d_inc_cw = p_all |> left_join(pb2[,c('patient','w_est','strata')],by="patient") |> mutate(strata_new=if_else(strata %in% c("HN KS 2010-2019", "HN No KS"),"HN",if_else(strata %in% c("MX-INCMNSZ KS 2010-2014","MX-INCMNSZ KS 2015-2019","MX-INCMNSZ No KS"),"MX",if_else(strata %in% c("MBARARA KS 2010-2014","MBARARA KS 2015-2019"),"MBARARA KS",if_else(strata %in% c("BR-IPEC KS 2010-2014","BR-IPEC KS 2015-2019"),"BR-KS",if_else(strata %in% c("FACES KS 2010-2019", "FACES No KS"),"FACES",strata))))))


ch_1=d_inc_cw |> select(patient,ks_ind,ks_ind_final,min_date,max_date,n,V,program,year,strata) |> group_by(patient,V,program,year,strata) |> summarize(ks_ind=max(ks_ind),ks_ind_final=max(ks_ind_final),min_date=min(min_date),max_date=max(max_date),n=sum(n)) |> mutate(pys=n/12,pys_final=n/12) 

ch_2=ch_1 |>left_join(unique(d_inc_cw[,c('patient','w_est')]))

################################################################################################################    
############## GR
### Year

mod_ehr_inc2 = glm(ks_ind ~ I(year-2010),offset = log(pys/1000),data= ch_2, family = poisson) 

  #### Raking
  IF_func <- function(fit){
    MM <- model.matrix(fit)
    Score.P   <- fit$y*MM - MM*exp(fit$linear.predictors)
    InfoMat.P <- t(MM*sqrt(exp(fit$linear.predictors))) %*% (MM*sqrt(exp(fit$linear.predictors)))/nrow(MM)
    inffunc <- (Score.P) %*% solve(InfoMat.P)
    inffunc
  }    

naiveInfl3 =  IF_func(mod_ehr_inc2)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(ch_2,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=~INF2,phase=2,calfun="raking") 
fit_gr_inc1 = svyglm(ks_ind_final ~ I(year-2010), offset = log(pys_final/1000), design=Ninflcal3, family = poisson)


#### Year and region

mod_ehr_inc2 = glm(ks_ind ~ I(year-2010) + program,offset = log(pys/1000),data= ch_2, family = poisson) 

naiveInfl3 =  IF_func(mod_ehr_inc2)[,-1]
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(ch_2,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc2 = svyglm(ks_ind_final ~ I(year-2010)+program, offset = log(pys_final/1000), design=Ninflcal3, family = poisson)



#### Year and region w/ interaction


mod_ehr_inc2 = glm(ks_ind ~ I(year-2010)*program,offset = log(pys/1000),data= ch_2, family = poisson) 

naiveInfl3 =  IF_func(mod_ehr_inc2)[,-1]
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(ch_2,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc3 = svyglm(ks_ind_final ~ I(year-2010)*program, offset = log(pys_final/1000), design=Ninflcal3, family = poisson)


lst= list(fit_gr_inc1,fit_gr_inc2,fit_gr_inc3)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients[-1]
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0))[-1])), betas + 1.96*(sqrt(diag(vcov(res0))[-1])))
  res2[[j]] <- exp(cis3)
}



ktab9_inc = cbind(OR = c(format(round(res2[[1]][,1],2),nsmall=2),"-","-"), CI_95_percent = c(paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),"-","-"),OR = c(format(round(res2[[2]][,1],2),nsmall=2),"-"), CI_95_percent = c(paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),"-"),OR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)))

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/ktab9_prev.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/ktab9_tte.Rda") 

ktab9 = cbind(ktab9_prev,ktab9_inc,ktab9_tte)

rownames(ktab9)=c('Year','East Africa','Year x East Africa')
ktab9 <- kable(ktab9,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2,"GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2,"GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2))%>%add_header_above(c(" ","Prevalence" = 6,"Incidence" = 6,"Mortality" = 6))



rownames(ktab9_inc)=c('Year','East Africa','Year x East Africa')
ktab9 <- kable(ktab9_inc,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2))%>%add_header_above(c(" ","Prevalence" = 6))
 


```


```{r}
##########################################################################################################################
##########################################################################################################################

#### Overall unadjusted GR weighted incidence ####

##########################################################################################################################
##########################################################################################################################

### overall

mod_ehr_inc2 = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw, family = poisson) 

  #### Raking
  IF_func <- function(fit){
    MM <- model.matrix(fit)
    Score.P   <- fit$y*MM - MM*exp(fit$linear.predictors)
    InfoMat.P <- t(MM*sqrt(exp(fit$linear.predictors))) %*% (MM*sqrt(exp(fit$linear.predictors)))/nrow(MM)
    inffunc <- (Score.P) %*% solve(InfoMat.P)
    inffunc
  }    

naiveInfl3 =  IF_func(mod_ehr_inc2)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_inc_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc_2 = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3, family = poisson)

overall_inc_ci=exp(fit_gr_inc_2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2)))*1.96)
overall_inc_est=exp(fit_gr_inc_2[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (1.14 KS cases) per 1000 person-years

##########################################################################################################################
##########################################################################################################################

### East Africa

mod_ehr_inc2_ea = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw[d_inc_cw$program==1,], family = poisson) 

naiveInfl3_ea =  IF_func(mod_ehr_inc2_ea)
colnames(naiveInfl3_ea)=paste("INF", 1:ncol(naiveInfl3_ea), sep="")

d14_ea=cbind(d_inc_cw[d_inc_cw$program==1,],naiveInfl3_ea) 

infs_eq1_ea <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3_ea), collapse = ' + ')))
designMF4_ea = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14_ea,subset=~V==1,method="approx")
Ninflcal3_ea<-calibrate(designMF4_ea,formula=infs_eq1_ea,phase=2,calfun="raking") 
fit_gr_inc_2_ea = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3_ea, family = poisson)

ea_inc_ci=exp(fit_gr_inc_2_ea[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2_ea)))*1.96)
ea_inc_est=exp(fit_gr_inc_2_ea[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (0.98 KS cases) per 1000 person-years


### Latin America

mod_ehr_inc2_cn = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw[d_inc_cw$program==0,], family = poisson) 

naiveInfl3_cn =  IF_func(mod_ehr_inc2_cn)
colnames(naiveInfl3_cn)=paste("INF", 1:ncol(naiveInfl3_cn), sep="")

d14_cn=cbind(d_inc_cw[d_inc_cw$program==0,],naiveInfl3_cn) 

infs_eq1_cn <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3_cn), collapse = ' + ')))
designMF4_cn = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata), data=d14_cn,subset=~V==1,method="approx")
Ninflcal3_cn<-calibrate(designMF4_cn,formula=infs_eq1_cn,phase=2,calfun="raking") 
fit_gr_inc_2_cn = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3_cn, family = poisson)

cn_inc_ci=exp(fit_gr_inc_2_cn[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2_cn)))*1.96)
cn_inc_est=exp(fit_gr_inc_2_cn[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (2.86 KS cases) per 1000 person-years

```



```{r}

##########################################################################################################################
##########################################################################################################################

#### Overall follow-up for patients who are on ART and not on ART, with unadjusted GR weighted incidence analyses ####

##########################################################################################################################
##########################################################################################################################

### overall

mod_ehr_inc2 = glm(ks_ind ~ 1,offset = log(pys/1000),data= ch_3, family = poisson) 

  #### Raking
  IF_func <- function(fit){
    MM <- model.matrix(fit)
    Score.P   <- fit$y*MM - MM*exp(fit$linear.predictors)
    InfoMat.P <- t(MM*sqrt(exp(fit$linear.predictors))) %*% (MM*sqrt(exp(fit$linear.predictors)))/nrow(MM)
    inffunc <- (Score.P) %*% solve(InfoMat.P)
    inffunc
  }    

naiveInfl3 =  IF_func(mod_ehr_inc2)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(ch_3,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(~strata_new,NULL), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc_2 = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3,family = poisson)

overall_inc_ci=exp(fit_gr_inc_2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2)))*1.96)
overall_inc_est=exp(fit_gr_inc_2[[1]])

ipw_c = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=designMF4, family = poisson)
overall_inc_ci=exp(ipw_c[[1]]+c(-1,1)*sqrt(diag(vcov(ipw_c)))*1.96)
overall_inc_est=exp(ipw_c[[1]])


################################################################################################################
################################################################################################################

### Checking into KS diagnosis near ART for IRIS

 d2 = d1 |> mutate(prevalent_remove = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60,1,0)) |> mutate(prevalent_remove_final = if_else(V==0,0, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60,1,0))) |> filter(prevalent_remove == 0 &  prevalent_remove_final==0 & (is.na(canc_d_final) | as.Date(canc_d_final)>=as.Date("2009-12-01"))) 


### incident cases before ART
d2 = d2 |> mutate(pre_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) > as.Date(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd),1,0))))

sum(d2$pre_ART)

sum(!is.na(d2$dis_d))


### incident cases during the first 90 days on ART

d2 = d2 |> mutate(early_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd)+90 & as.Date(dis_d) > as.Date(art_sd),1,0))))

sum(d2$early_ART)

### incident cases >90 after ART start

d2 = d2 |> mutate(late_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd)+90,0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) > as.Date(art_sd)+90,1,0))))

sum(d2$late_ART)

### 791/816 on ART

# 140 diagnosed with incident KS cases before ART start
# 148 diagnosed with incident KS cases within or equal to 90 after ART start
# 503 diagnosed with incident KS cases >90 after ART start



d_ch=d_inc_cw |> group_by(patient,ks_ind,ks_ind_final,V) |> summarize(ct=n()) |> filter(ks_ind==1 | ks_ind_final==1) |> arrange(desc(ct)) |> left_join()


patients_sum_1 = d_inc_cw |> group_by(patient,program,male) |> summarize(time_os=sum(pys),cd4=last(cd4_rt_init_imp),art=max(art_ind), age_es=last(age), inc=max(ks_ind)) |> left_join(d1[,c('patient','dis_d','art_sd')],join_by(patient))

patients_sum_2 = d_inc_cw |> filter(V==1) |> group_by(patient,program,male_final,w_est) |> summarize(time_os=sum(pys_final),cd4=last(cd4_rt_imp_final),art=max(art_ind_final), age_es=last(age_final), inc=max(ks_ind_final)) |> left_join(d1[,c('patient','dis_d','art_sd','canc_d_final','recart_d_final')],join_by(patient))

############################################################################################################################################################################################################

### phase 1 IRIS checks
### incident cases before ART
d2 = patients_sum_1 |> mutate(pre_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) > as.Date(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd),1,0))))  

### incident cases during the first 90 days on ART

d2 = d2 |> mutate(early_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd)+90 & as.Date(dis_d) > as.Date(art_sd),1,0))))

### incident cases >90 after ART start

d2 = d2 |> mutate(late_ART=if_else(is.na(dis_d) | is.na(art_sd),0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) <= as.Date(art_sd)+90,0,if_else(!is.na(dis_d) & !is.na(art_sd) & as.Date(dis_d) > as.Date(art_sd)+90,1,0))))

############################################################################################################################################################################################################

### phase 2 IRIS checks
### incident cases before ART
dv2 = patients_sum_2 |> mutate(pre_ART=if_else(is.na(canc_d_final) | is.na(recart_d_final),0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) > as.Date(recart_d_final),0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) <= as.Date(recart_d_final),1,0))))  

### incident cases during the first 90 days on ART

dv2 = dv2 |> mutate(early_ART=if_else(is.na(canc_d_final) | is.na(recart_d_final),0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) <= as.Date(recart_d_final),0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) <= as.Date(recart_d_final)+90 & as.Date(canc_d_final) > as.Date(recart_d_final),1,0))))

### incident cases >90 after ART start

dv2 = dv2 |> mutate(late_ART=if_else(is.na(canc_d_final) | is.na(recart_d_final),0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) <= as.Date(recart_d_final)+90,0,if_else(!is.na(canc_d_final) & !is.na(recart_d_final) & as.Date(canc_d_final) > as.Date(recart_d_final)+90,1,0))))



```