---
title: "KS Data"
author: "Josh"
output: html_document
---


```{r echo=FALSE}

library(dplyr)
library(dtplyr)
library(data.table)
library(splines)
library(survey)
library(mitools)
library(mvtnorm)
library(kableExtra)

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cohort_imp1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4_1.Rda") 
#all_cd4_1 = all_cd4_1 |> filter(!is.na(month_avg_cd4))
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4.Rda") 

patients_all = fread("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Sampling_frame/patients_all.csv")
names(patients_all)="patient"

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long.Rda") 



all_val_long4$R=1

d_1 = all_cohort_imp1 |> filter(patient %in% all_val_long$patient)  |> left_join(all_val_long4[,c('patient','R')]) |> count(patient,stop_d,program,death_y,R) |> mutate(n=NULL,R=if_else(is.na(R),0,R))


#### Single imputation for filling in missing cd4 values in phase 1 and phase 2

#### use one row for all patients in cohort 
d = all_cohort_imp1 |> inner_join(patients_all,by="patient")  
  
## Allow patients w/ dis_d >= as.Date("2009-12-01") for date shift from East Africa
d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  

d1$enrol_d_year_month= format(as.Date(d1$enrol_d), "%Y-%m")

## Add unvalidated CD4 
d2 = d1 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by="patient") |> mutate(cd4_d=if_else(!is.na(year_month),paste(year_month, "-01", sep=""),NA)) |>mutate(cd4_d=as.Date(cd4_d), Diff= cd4_d-as.Date(enrol_d)) |> mutate(Diff=if_else(Diff>-183,Diff,NA),Diff=abs(Diff))

### limit to date of cd4 closest to enrollment (6 months before to 12 months after) 
d3_1= d2|> group_by(patient) |> slice_min(Diff, with_ties = F) |> mutate(cd4_rt=if_else(!is.na(Diff) & !is.na(month_avg_cd4),sqrt(month_avg_cd4),NA))


## Add validated CD4 

d4 = d3_1 |> left_join(all_val_long4[,c("patient","month_avg_cd4_final","cd4_d_final")],by="patient") 

#d4_1 = d4|> mutate(Diff1= if_else(!is.na(cd4_d_final),cd4_d_final-enrol_d_final,NA))

d4$Diff1=d4$cd4_d_final - d4$enrol_d_final 
d4$Diff1=ifelse(d4$Diff1 >-183,d4$Diff1,NA)
d4$Diff1=abs(d4$Diff1)

#d4 = d4|> mutate(Diff1=if_else(Diff1>-183,Diff1,NA),Diff1=abs(Diff1))
  
d5= d4|> group_by(patient) |> slice_min(Diff1, with_ties = F) |> mutate(cd4_rt_final=if_else(!is.na(Diff1) & !is.na(month_avg_cd4_final),sqrt(month_avg_cd4_final),NA))


d6 = d5 |> lazy_dt() |> mutate(cd4_rt=if_else(Diff < 183,cd4_rt,NA),cd4_rt_final=if_else(Diff1 < 183,cd4_rt_final,NA)) |> mutate(age=as.numeric(round((as.Date(enrol_d)-as.Date(birth_d))/365.25,1)), year = if_else(as.Date(enrol_d)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(enrol_d,1,4))),art_ind = if_else(is.na(art_sd),0,if_else(as.Date(art_sd)<as.Date(enrol_d),1,0)),age_final=as.numeric(round((as.Date(enrol_d_final)-as.Date(birth_d_final))/365.25,1)), year_final = if_else(as.Date(enrol_d_final)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(enrol_d_final,1,4))),art_ind_final = if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0))) |> ungroup() |> as.data.frame()

## KS indicator
d6 = d6 |> lazy_dt()|> mutate(ks_ind = if_else(!is.na(dis_d),1,0)) |> ungroup() |> as.data.frame()

## KS indicator validated (one patient had canc_d_final in 7/2009, make not KS diagnosis)
d6 = d6  |> lazy_dt()  |> mutate(ks_ind_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final),1,0))) |> ungroup() |> as.data.frame()

#############################################################################################################################
#### prevalence indicator
## KS indicator
d6 = d6 |> lazy_dt() |> mutate(prevalent = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60 & dis_d >= enrol_d - 60,1,0)) |> mutate(prevalent_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60 & canc_d_final >= enrol_d_final - 60,1,0))) |> ungroup() |> as.data.frame()

## remove KS cases >60 days before enrollment (54 instances between phase 1 and phase2)
d6 = d6 |> mutate(remove=if_else((!is.na(canc_d_final) & canc_d_final < enrol_d_final - 60) | (!is.na(dis_d) & dis_d < enrol_d - 60),1,0)) |> filter(remove==0)

###############################################

 
d6 = d6  |> lazy_dt() |> filter(as.Date(enrol_d)>=as.Date("2010-01-01") | (as.Date(enrol_d)>=as.Date("2009-12-01") & program==1)) |> filter(V==0 | (V==1 & (as.Date(enrol_d_final)>=as.Date("2010-01-01") | (as.Date(enrol_d_final)>=as.Date("2009-12-01") & program==1)))) |> ungroup() |> as.data.frame()



```


```{r}

### single imputation for missing CD4 values 

    ### imputation for phase 1 cd4 values based on error prone variables
    mod5 = lm(cd4_rt ~  male +program+ ns(age,df=4) + year +art_ind +prevalent, data= d6) 
    #ch=d6[!is.na(d6$cd4_rt),]
   ## to easily get design matrix for the full cohort
    d6_1 = d6 |> mutate(cd4_rt=1)
    v3=model.matrix(terms(mod5),d6_1)
    beta2 = mod5$coefficients
    vcov2 = vcov(mod5)
    rmvs2=rmvnorm(n=1,beta2,vcov2)
    rmvs2 = as.vector(rmvs2)
    cd4_rt_new = as.vector((v3 %*% rmvs2) + sample(resid(mod5),1))
    d6$cd4_rt_init_imp=if_else(is.na(d6$cd4_rt),cd4_rt_new,d6$cd4_rt)
    ### any imputed CD4<0 assign a 1
    d6$cd4_rt_init_imp=if_else(d6$cd4_rt_init_imp<0,1,d6$cd4_rt_init_imp)

  ### imputation for phase 2 cd4 values
  
  mod6 = lm(cd4_rt_final ~  male_final +program+ ns(age_final,df=4) + ns(cd4_rt_init_imp,df=4) + year_final +art_ind_final +prevalent_final, data= d6[d6$V==1,])
    ## to easily get design matrix for phase 2
  d6_1 = d6[d6$V==1,] |> mutate(cd4_rt_final=1)
   v4=model.matrix(terms(mod6),d6_1)
  beta2 = mod6$coefficients
  vcov2 = vcov(mod6)
  rmvs2=rmvnorm(n=1,beta2,vcov2)
  rmvs2 = as.vector(rmvs2)
  cd4_rt_final_new = as.vector((v4 %*% rmvs2) + sample(resid(mod6),1))
  d6_phase2 = d6[d6$V==1,]
  d6_phase2$cd4_rt_imp_final=if_else(is.na(d6_phase2$cd4_rt_final),cd4_rt_final_new,d6_phase2$cd4_rt_final)
  
  d6_phase1 = d6 |> filter(V!=1) |> mutate(cd4_rt_imp_final=NA)
  
  d7 = rbind(d6_phase1,d6_phase2) 



d_2 = d_1 |> filter(patient %in% d7$patient)
mod_w = glm(R ~ stop_d + program + death_y, family=binomial,data = d_2)
mod_p<- mod_w$fitted.values
d_p = data.frame(d_2,p_est=mod_p)


#################################################################################################################  
#### IPW with original design weights for the entire sample frame
#load(file="~/Desktop/PhD/Research/KS_Data/Code/wgts_by_hand.Rda")

load(file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/strata.Rda")

## nonresponse probabilities
#load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/d_p.Rda") 
#d_prev_c= merge(x=d7,y=d3,all.x=TRUE,by="patient")
#d_prev_c= merge(x=d_prev_c,y=d_p[,c('patient','p_est')],all.x=TRUE,by="patient")

d_prev_c= merge(x=d7,y=d_c2,all.x=TRUE,by="patient")

### collapsing strata so we can use them in twophase() to estimate correct variance (strata_new)
d_prev_c= merge(x=d_prev_c,y=d_p[,c('patient','p_est')],all.x=TRUE,by="patient") |> mutate(strata_new=if_else(strata %in% c("HN KS 2010-2019","HN No KS"),"HN",if_else(strata %in% c("MX-INCMNSZ KS 2010-2014","MX-INCMNSZ KS 2015-2019"),"MX KS",strata)))


#designMF5 = twophase(id=list(~1,~1),weights=list(~1,~w),subset=~V==1, data=d_prev_c,method="approx")
#ipw_prev_c_orig = svyglm(prevalent_final ~ male_final + program + I(age_final/10) + year_final + art_ind_final + cd4_rt_imp_final, design=designMF5, family = quasibinomial())

#################################################################################################################
#### IPW with estimated weights including nonresponse probabilities from the prevalence at enrollment analysis cohort

mod_w = glm(V ~ strata, family=binomial,data = d_prev_c)
mod_p <- mod_w$fitted.values
d_prev_cw = data.frame(d_prev_c,p_est_overall=mod_p)
d_prev_cw = d_prev_cw |> mutate(w_est = 1/(p_est_overall*p_est))

designMF6 = twophase(id=list(~1,~1),weights=list(~1,~w_est),subset=~V==1, data=d_prev_cw,method="approx")
ipw_prev_c2 = svyglm(prevalent_final ~ male_final*program + I(age_final/10) + I(year_final-2010) + art_ind_final + cd4_rt_imp_final, design=designMF6, family = quasibinomial())


#################################################################################################################
##### Generalized raking

#### Year as covariate

mod_ehr_prev = glm(prevalent ~ I(year-2010), data= d_prev_cw, family = binomial)

#######  w/o intercept in gr calibration, just considering efficiency for coef. ests. 
## Tong's function
inf.fun <- function(fit) {
  dm <- model.matrix(fit)
  Ihat <- (t(dm) %*% (dm * fit$fitted.values * (1 - fit$fitted.values))) / nrow(dm)
  ## influence function
  infl <- (dm * resid(fit, type = "response")) %*% solve(Ihat)
  infl
}

naiveInfl3 =  inf.fun(mod_ehr_prev)

colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=~INF2,phase=2,calfun="raking") 
fit_gr_prev1 = svyglm(prevalent_final ~ I(year_final-2010), design=Ninflcal3, family = quasibinomial())


#### Year and region

mod_ehr_prev = glm(prevalent ~ I(year-2010) +program, data= d_prev_cw, family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)[,-1] 
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3)

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ I(year_final-2010)+program, design=Ninflcal3, family = quasibinomial())

#### Year and region w/ interaction

mod_ehr_prev = glm(prevalent ~ I(year-2010)*program, data= d_prev_cw, family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)[,-1] 
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3)

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev3 = svyglm(prevalent_final ~ I(year_final-2010)*program, design=Ninflcal3, family = quasibinomial())


lst= list(fit_gr_prev1,fit_gr_prev2,fit_gr_prev3)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients[-1]
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0))[-1])), betas + 1.96*(sqrt(diag(vcov(res0))[-1])))
  res2[[j]] <- exp(cis3)
}


ktab9_prev = cbind(OR = c(format(round(res2[[1]][,1],2),nsmall=2),"-","-"), CI_95_percent = c(paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),"-","-"),OR = c(format(round(res2[[2]][,1],2),nsmall=2),"-"), CI_95_percent = c(paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),"-"),OR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)))


#save(ktab9_prev,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/ktab9_prev.Rda") 


rownames(ktab9_prev)=c('Year','East Africa','Year x East Africa')
ktab9 <- kable(ktab9_prev,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","GR Year" = 2,"GR Year and Region" = 2,"GR Year x Region" = 2))%>%add_header_above(c(" ","Prevalence" = 6))


```






```{r}

####################################################################################################################################################################################################################################################

#### Overall unadjusted GR weighted prevalence ####

##########################################################################################################################
##########################################################################################################################

### overall

mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw, family = binomial)

#######  w/o intercept in gr calibration, just considering efficiency for coef. ests. 
## Tong's function
inf.fun <- function(fit) {
  dm <- model.matrix(fit)
  Ihat <- (t(dm) %*% (dm * fit$fitted.values * (1 - fit$fitted.values))) / nrow(dm)
  ## influence function
  infl <- (dm * resid(fit, type = "response")) %*% solve(Ihat)
  infl
}

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
overall_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
overall_prev_ci_prob=overall_prev_ci_odds/(1+overall_prev_ci_odds)
overall_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))

  
### by region
  
#### East Africa
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$program==1,], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$program==1,],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))
  

#### Latin America
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$program==0,], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$program==0,],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
cn_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
cn_prev_ci_prob=cn_prev_ci_odds/(1+cn_prev_ci_odds)
cn_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))

```

```{r}
### GR for early and later in the study
  
#### 2010
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$year=="2010",], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$year=="2010",],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))


#### 2018
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$year=="2018",], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$year=="2018",],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))

#############################################################################################################
#############################################################################################################

### by year and program
  
#### 2010 and EA
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$year=="2010" & d_prev_cw$program==1,], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$year=="2010" & d_prev_cw$program==1,],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))


#### 2018
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$year=="2018",], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$year=="2018",],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))





```




